apiVersion: v1
kind: Namespace
metadata:
  name: redis

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: red-conf
  namespace: redis
data:
  redis.conf: |
    pidfile /data/redis.pid
    port 6379
    tcp-backlog 30000
    timeout 0
    tcp-keepalive 10
    loglevel notice
    logfile /data/redis.log
    databases 16
    requirepass 123456
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
  namespace: redis
  labels:
    app: redis-dep
spec:
  replicas: 1
  template:
    metadata:
      name: redis-dep
      labels:
        app: redis-dep
    spec:
      containers:
        - name: redis-dep
          image: redis:7.0.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/usr/local/etc"
              name: foo
          command:
            - "redis-server"
          args:
            - "/usr/local/etc/redis/redis.conf"
      volumes:
        - name: foo
          configMap:
            name: red-conf
            items:
              - key: redis.conf
                path: redis/redis.conf
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis-dep

---
apiVersion: v1
kind: Service
metadata:
  name: redis-dep
  namespace: redis
spec:
  selector:
    app: redis-dep
  ports:
    - port: 30002
      nodePort: 30001
      targetPort: 6379
  type: NodePort